export const salons = [
  {
    id: 1,
    image: '/space-one.jpg',
    price: '$12/hr',
    name: 'Leo Barber Shop',
    location: 'Chicago, IL',
    distance: '0.5 mi away',
    url: 'leo-barber-shop',
  },
  {
    id: 2,
    image: '/salon-two.jpg',
    price: '$15/hr',
    name: 'Glamour Cuts',
    location: 'Chicago, IL',
    distance: '1.2 mi away',
    url: 'glamour-cuts',
  },
  {
    id: 3,
    image: '/salon-three.jpg',
    price: '$18/hr',
    name: 'Trendy Styles',
    location: 'Chicago, IL',
    distance: '2.3 mi away',
    url: 'trendy-styles',
  },
  {
    id: 4,
    image: '/salon-four.jpg',
    price: '$20/hr',
    name: 'Elegant Hair',
    location: 'Chicago, IL',
    distance: '0.8 mi away',
    url: 'elegant-hair',
  },
  {
    id: 5,
    image: '/salon-five.jpg',
    price: '$14/hr',
    name: 'Classic Cuts',
    location: 'Chicago, IL',
    distance: '3.0 mi away',
    url: 'classic-cuts',
  },
  {
    id: 6,
    image: '/salon-six.jpg',
    price: '$22/hr',
    name: 'Chic Salon',
    location: 'Chicago, IL',
    distance: '1.5 mi away',
    url: 'chic-salon',
  },
  {
    id: 7,
    image: '/salon-seven.jpg',
    price: '$25/hr',
    name: 'Luxury Hair',
    location: 'Chicago, IL',
    distance: '4.0 mi away',
    url: 'luxury-hair',
  },
  {
    id: 8,
    image: '/salon-one.jpg',
    price: '$30/hr',
    name: 'Elite Styles',
    location: 'Chicago, IL',
    distance: '2.7 mi away',
    url: 'elite-styles',
  },
];

export const weekDays = [
  { day: 'Monday', hours: 'Closed' },
  { day: 'Tuesday', hours: 'Closed' },
  { day: 'Wednesday', hours: '12:00 PM - 2:00 PM' },
  { day: 'Thursday', hours: '12:00 PM - 2:00 PM' },
  { day: 'Friday', hours: '12:00 PM - 5:00 PM' },
  { day: 'Saturday', hours: '12:00 PM - 5:00 PM' },
  { day: 'Sunday', hours: '9:00 AM - 5:00 PM' },
];

export const pendingSalons = [
  {
    id: 15,
    image: '/salon-five.jpg',
    price: '$16/hr',
    name: 'Prime Cuts',
    location: 'Chicago, IL',
    distance: '3.5 mi away',
    url: 'prime-cuts',
  },
  {
    id: 16,
    image: '/salon-six.jpg',
    price: '$24/hr',
    name: 'Urban Chic',
    location: 'Chicago, IL',
    distance: '1.8 mi away',
    url: 'urban-chic',
  },
  {
    id: 17,
    image: '/salon-seven.jpg',
    price: '$28/hr',
    name: 'Prestige Hair',
    location: 'Chicago, IL',
    distance: '4.2 mi away',
    url: 'prestige-hair',
  },
  {
    id: 18,
    image: '/salon-one.jpg',
    price: '$32/hr',
    name: 'Elite Glamour',
    location: 'Chicago, IL',
    distance: '3.0 mi away',
    url: 'elite-glamour',
  },
];

export const pastSalons = [
  {
    id: 21,
    image: '/space-one.jpg',
    price: '$14/hr',
    name: 'Modern Mane Studio',
    location: 'Chicago, IL',
    distance: '1.0 mi away',
    url: 'modern-mane-studio',
    status: 'Completed',
  },
  {
    id: 22,
    image: '/salon-two.jpg',
    price: '$17/hr',
    name: 'Chic Cuts',
    location: 'Chicago, IL',
    distance: '1.5 mi away',
    url: 'chic-cuts',
    status: 'Canceled',
  },
  {
    id: 23,
    image: '/salon-three.jpg',
    price: '$19/hr',
    name: 'Urban Trim',
    location: 'Chicago, IL',
    distance: '2.7 mi away',
    url: 'urban-trim',
    status: 'Completed',
  },
  {
    id: 24,
    image: '/salon-four.jpg',
    price: '$22/hr',
    name: 'Lux Hair Lounge',
    location: 'Chicago, IL',
    distance: '0.9 mi away',
    url: 'lux-hair-lounge',
    status: 'Completed',
  },
  {
    id: 25,
    image: '/salon-five.jpg',
    price: '$16/hr',
    name: 'Prime Cuts',
    location: 'Chicago, IL',
    distance: '3.5 mi away',
    url: 'prime-cuts',
    status: 'Canceled',
  },
];

export const weekDaysShort = [
  { day: 'Monday', short: 'Mon' },
  { day: 'Tuesday', short: 'Tue' },
  { day: 'Wednesday', short: 'Wed' },
  { day: 'Thursday', short: 'Thu' },
  { day: 'Friday', short: 'Fri' },
  { day: 'Saturday', short: 'Sat' },
  { day: 'Sunday', short: 'Sun' },
];
