export const salons = [
  {
    id: 1,
    image: '/space-one.jpg',
    price: '$12/hr',
    name: 'Leo Barber Shop',
    location: 'Chicago, IL',
    distance: '0.5 mi away',
    url: 'leo-barber-shop',
  },
  {
    id: 2,
    image: '/salon-two.jpg',
    price: '$15/hr',
    name: 'Glamour Cuts',
    location: 'Chicago, IL',
    distance: '1.2 mi away',
    url: 'glamour-cuts',
  },
  {
    id: 3,
    image: '/salon-three.jpg',
    price: '$18/hr',
    name: 'Trendy Styles',
    location: 'Chicago, IL',
    distance: '2.3 mi away',
    url: 'trendy-styles',
  },
  {
    id: 4,
    image: '/salon-four.jpg',
    price: '$20/hr',
    name: 'Elegant Hair',
    location: 'Chicago, IL',
    distance: '0.8 mi away',
    url: 'elegant-hair',
  },
  {
    id: 5,
    image: '/salon-five.jpg',
    price: '$14/hr',
    name: 'Classic Cuts',
    location: 'Chicago, IL',
    distance: '3.0 mi away',
    url: 'classic-cuts',
  },
  {
    id: 6,
    image: '/salon-six.jpg',
    price: '$22/hr',
    name: 'Chic Salon',
    location: 'Chicago, IL',
    distance: '1.5 mi away',
    url: 'chic-salon',
  },
  {
    id: 7,
    image: '/salon-seven.jpg',
    price: '$25/hr',
    name: 'Luxury Hair',
    location: 'Chicago, IL',
    distance: '4.0 mi away',
    url: 'luxury-hair',
  },
  {
    id: 8,
    image: '/salon-one.jpg',
    price: '$30/hr',
    name: 'Elite Styles',
    location: 'Chicago, IL',
    distance: '2.7 mi away',
    url: 'elite-styles',
  },
];
